from __future__ import annotations

from typing import Tuple

from .models import Gender, LanguageCode, VoiceInfo
from .ratings import (
    GRADE_A,
    GRADE_A_MINUS,
    GRADE_B_MINUS,
    GRADE_C,
    GRADE_C_MINUS,
    GRADE_C_PLUS,
    GRADE_D,
    GRADE_F_PLUS,
)

# American English: 11F 9M

VOICE_INFOS: Tuple[VoiceInfo, ...] = (
    # Female (af_*)
    VoiceInfo(
        voice_id="af_heart",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Heart",
        traits="premium, polished, balanced",
        target_quality="A",
        training_minutes=None,
        overall_grade=GRADE_A,
        best_for=["storytelling", "commentary", "hero-narrator"],
        recommended=True,
    ),
    VoiceInfo(
        voice_id="af_alloy",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Alloy",
        traits="clear, professional, neutral female voice",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C,
        best_for=["commentary", "explanatory", "neutral"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_aoede",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Aoede",
        traits="smooth, melodic, expressive",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["storytelling", "dramatic", "commentary"],
        recommended=True,
    ),
    VoiceInfo(
        voice_id="af_bella",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Bella",
        traits="warm, friendly, charismatic",
        target_quality="A",
        training_minutes=None,
        overall_grade=GRADE_A_MINUS,
        best_for=["storytelling", "commentary", "wholesome"],
        recommended=True,
    ),
    VoiceInfo(
        voice_id="af_jessica",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Jessica",
        traits="natural but less polished, experimental",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental", "character"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_kore",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Kore",
        traits="steady, slightly serious, neutral",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["commentary", "analysis", "neutral"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_nicole",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Nicole",
        traits="studio-style, headphone-optimized, clear",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_B_MINUS,
        best_for=["storytelling", "commentary", "long-form"],
        recommended=True,
    ),
    VoiceInfo(
        voice_id="af_nova",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Nova",
        traits="bright, energetic, modern",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C,
        best_for=["energetic", "short-form", "hooks"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_river",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="River",
        traits="soft, calm, slightly distant",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["relaxed", "background", "experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_sarah",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Sarah",
        traits="steady, approachable, mildly expressive",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["commentary", "explanatory"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="af_sky",
        lang=LanguageCode.AMERICAN,
        gender=Gender.FEMALE,
        label="Sky",
        traits="light, airy, a bit thin",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_MINUS,
        best_for=["short-form", "quirky", "experimental"],
        recommended=False,
    ),
    # Male (am_*)
    VoiceInfo(
        voice_id="am_adam",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Adam",
        traits="rougher, experimental male voice",
        target_quality="D",
        training_minutes=None,
        overall_grade=GRADE_F_PLUS,
        best_for=["experimental", "character"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_echo",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Echo",
        traits="neutral male, somewhat flat",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["background", "experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_eric",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Eric",
        traits="conversational, informal, less polished",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["casual", "experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_fenrir",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Fenrir",
        traits="strong, dramatic, authoritative",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["dramatic", "storytelling", "commentary"],
        recommended=True,
    ),
    VoiceInfo(
        voice_id="am_liam",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Liam",
        traits="approachable, relatively neutral",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["casual", "experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_michael",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Michael",
        traits="steady, broadcast-like",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["commentary", "analysis"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_onyx",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Onyx",
        traits="dark, heavier, character-like",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["villain", "character", "experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_puck",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Puck",
        traits="playful, slightly mischievous",
        target_quality="B",
        training_minutes=None,
        overall_grade=GRADE_C_PLUS,
        best_for=["comic", "lighthearted", "short-form"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="am_santa",
        lang=LanguageCode.AMERICAN,
        gender=Gender.MALE,
        label="Santa (US)",
        traits="seasonal, character voice, jovial",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_C_MINUS,
        best_for=["seasonal", "character", "fun"],
        recommended=False,
    ),
)
