from __future__ import annotations

from typing import Tuple

from .models import Gender, LanguageCode, VoiceInfo
from .ratings import GRADE_D

# Mandarin Chinese: 4F 4M, all C/ MM / D 

VOICE_INFOS: Tuple[VoiceInfo, ...] = (
    VoiceInfo(
        voice_id="zf_xiaobei",
        lang=LanguageCode.CHINESE,
        gender=Gender.FEMALE,
        label="Xiaobei",
        traits="Mandarin female, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zf_xiaoni",
        lang=LanguageCode.CHINESE,
        gender=Gender.FEMALE,
        label="Xiaoni",
        traits="Mandarin female, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zf_xiaoxiao",
        lang=LanguageCode.CHINESE,
        gender=Gender.FEMALE,
        label="Xiaoxiao",
        traits="Mandarin female, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zf_xiaoyi",
        lang=LanguageCode.CHINESE,
        gender=Gender.FEMALE,
        label="Xiaoyi",
        traits="Mandarin female, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zm_yunjian",
        lang=LanguageCode.CHINESE,
        gender=Gender.MALE,
        label="Yunjian",
        traits="Mandarin male, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zm_yunxi",
        lang=LanguageCode.CHINESE,
        gender=Gender.MALE,
        label="Yunxi",
        traits="Mandarin male, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zm_yunxia",
        lang=LanguageCode.CHINESE,
        gender=Gender.MALE,
        label="Yunxia",
        traits="Mandarin male, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
    VoiceInfo(
        voice_id="zm_yunyang",
        lang=LanguageCode.CHINESE,
        gender=Gender.MALE,
        label="Yunyang",
        traits="Mandarin male, limited training data",
        target_quality="C",
        training_minutes=None,
        overall_grade=GRADE_D,
        best_for=["experimental"],
        recommended=False,
    ),
)
